name: gradle-test

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

permissions:
  contents: write

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit Tests (Gradle)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true }}

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload JUnit XML results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: junit-xml
          path: |
            app/build/test-results/testDebugUnitTest/**/*.xml
            app/build/test-results/testReleaseUnitTest/**/*.xml
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload HTML test report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report-html
          path: |
            app/build/reports/tests/testDebugUnitTest/**
            app/build/reports/tests/testReleaseUnitTest/**
          if-no-files-found: ignore
          retention-days: 7
